package net.mwel.thewitchermod.item;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.item.Item;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import net.mwel.thewitchermod.TheWitcherMod;
import net.mwel.thewitchermod.item.type.*;




public class ModItems{


/*    Items used in Vanilla as well */
//    public static final Item coal = registerItem("coal", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item copper_ingot = registerItem("copper_ingot", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item copper_ore = registerItem("copper_ore", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item diamond = registerItem("diamond", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item emerald = registerItem("emerald", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item gold_nugget = registerItem("gold_nugget", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item gold_ore = registerItem("gold_ore", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item iron_ingot = registerItem("iron_ingot", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item iron_ore = registerItem("iron_ore", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item feather = registerItem("feather", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item empty_bottle = registerItem("empty_bottle", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));

    
//    public static final Item lesser_runestone = registerItem("lesser_runestone", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
//    public static final Item lesser_infusion_glyph = registerItem("lesser_infusion_glyph", new Item(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));



    //Components
    public static final Item acid_extract = registerItem("acid_extract", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item amber = registerItem("amber", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item amber_dust = registerItem("amber_dust", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item amber_fragment = registerItem("amber_fragment", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item amethyst = registerItem("amethyst", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item amethyst_dust = registerItem("amethyst_dust", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item azurite = registerItem("azurite", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item black_pearl = registerItem("black_pearl", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item black_pearl_dust = registerItem("black_pearl_dust", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item chitinous_shell = registerItem("chitinous_shell", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item copper_plate = registerItem("copper_plate", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item cotton = registerItem("cotton", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item cupronickel_ore = registerItem("cupronickel_ore", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item cured_draconid_leather = registerItem("cured_draconid_leather", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item cured_leather = registerItem("cured_leather", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dark_iron_ingot = registerItem("dark_iron_ingot", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dark_iron_ore = registerItem("dark_iron_ore", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dark_iron_plate = registerItem("dark_iron_plate", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dark_steel_ingot = registerItem("dark_steel_ingot", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dark_steel_plate = registerItem("dark_steel_plate", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item diamond_dust = registerItem("diamond_dust", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dimeritium_ingot = registerItem("dimeritium_ingot", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dimeritium_ore = registerItem("dimeritium_ore", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dimeritium_plate = registerItem("dimeritium_plate", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dragon_scales = registerItem("dragon_scales", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dwarven_armorers_tools = registerItem("dwarven_armorers_tools", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dwarven_whetstone = registerItem("dwarven_whetstone", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dye = registerItem("dye", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dye_solution = registerItem("dye_solution", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item elven_armorers_tools = registerItem("elven_armorers_tools", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item elven_whetstone = registerItem("elven_whetstone", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item emerald_dust = registerItem("emerald_dust", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item endrega_armor_plate = registerItem("endrega_armor_plate", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item enriched_dimeritium_ingot = registerItem("enriched_dimeritium_ingot", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item enriched_dimeritium_ore = registerItem("enriched_dimeritium_ore", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item enriched_dimeritium_plate = registerItem("enriched_dimeritium_plate", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item fiber = registerItem("fiber", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item flawless_amber = registerItem("flawless_amber", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item flawless_amethyst = registerItem("flawless_amethyst", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item flawless_diamond = registerItem("flawless_diamond", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item flawless_emerald = registerItem("flawless_emerald", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item flawless_ruby = registerItem("flawless_ruby", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item flawless_sapphire = registerItem("flawless_sapphire", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item fur_scrap = registerItem("fur_scrap", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item glowing_ingot = registerItem("glowing_ingot", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item glowing_ore = registerItem("glowing_ore", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item gnomish_armorers_tools = registerItem("gnomish_armorers_tools", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item gnomish_whetstone = registerItem("gnomish_whetstone", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item green_gold_dust = registerItem("green_gold_dust", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item green_gold_ingot = registerItem("green_gold_ingot", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item green_gold_ore = registerItem("green_gold_ore", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item green_gold_plate = registerItem("green_gold_plate", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item hardened_leather = registerItem("hardened_leather", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item hardened_timber = registerItem("hardened_timber", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item hunk_of_nickel = registerItem("hunk_of_nickel", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item infused_crystal = registerItem("infused_crystal", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item infused_dust = registerItem("infused_dust", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item infused_shard = registerItem("infused_shard", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item infused_slyzard_hide = registerItem("infused_slyzard_hide", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item leather_scraps = registerItem("leather_scraps", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item leather_straps = registerItem("leather_straps", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item linen = registerItem("linen", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item malachite = registerItem("malachite", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item meteorite_ingot = registerItem("meteorite_ingot", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item meteorite_ore = registerItem("meteorite_ore", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item meteorite_silver_ingot = registerItem("meteorite_silver_ingot", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item meteorite_silver_plate = registerItem("meteorite_silver_plate", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_blood = registerItem("monster_blood", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_bone = registerItem("monster_bone", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_brain = registerItem("monster_brain", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_carapace = registerItem("monster_carapace", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_claw = registerItem("monster_claw", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_ear = registerItem("monster_ear", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_egg = registerItem("monster_egg", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_essence = registerItem("monster_essence", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_eye = registerItem("monster_eye", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_feather = registerItem("monster_feather", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_hair = registerItem("monster_hair", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_heart = registerItem("monster_heart", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_hide = registerItem("monster_hide", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_liver = registerItem("monster_liver", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_pincer = registerItem("monster_pincer", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_saliva = registerItem("monster_saliva", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_spore = registerItem("monster_spore", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_stomach = registerItem("monster_stomach", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_tongue = registerItem("monster_tongue", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_tooth = registerItem("monster_tooth", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_vine = registerItem("monster_vine", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item monster_wing = registerItem("monster_wing", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nails = registerItem("nails", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nickel_ore = registerItem("nickel_ore", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item oil = registerItem("oil", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item orichalcum_dust = registerItem("orichalcum_dust", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item orichalcum_ingot = registerItem("orichalcum_ingot", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item orichalcum_ore = registerItem("orichalcum_ore", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item orichalcum_plate = registerItem("orichalcum_plate", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item pearl = registerItem("pearl", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item powdered_monster_tissue = registerItem("powdered_monster_tissue", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item powdered_pearl = registerItem("powdered_pearl", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item resin = registerItem("resin", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item rope = registerItem("rope", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item ruby = registerItem("ruby", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item ruby_dust = registerItem("ruby_dust", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item sap = registerItem("sap", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item sapphire = registerItem("sapphire", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item sapphire_dust = registerItem("sapphire_dust", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item silk = registerItem("silk", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item silver_dust = registerItem("silver_dust", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item silver_ingot = registerItem("silver_ingot", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item silver_ore = registerItem("silver_ore", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item silver_plate = registerItem("silver_plate", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item siren_vocal_cords = registerItem("siren_vocal_cords", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item steel_ingot = registerItem("steel_ingot", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item steel_line = registerItem("steel_line", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item steel_plate = registerItem("steel_plate", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item thread = registerItem("thread", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item timber = registerItem("timber", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item twine = registerItem("twine", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item unrefined_copper_ore = registerItem("unrefined_copper_ore", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item venom_extract = registerItem("venom_extract", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item wax = registerItem("wax", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item wire = registerItem("wire", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item zerrikanian_powder = registerItem("zerrikanian_powder", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));

    //Ingredients
    public static final Item acid_archespore_juice = registerItem("acid_archespore_juice", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item aether = registerItem("aether", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item albedo = registerItem("albedo", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item alchemists_powder = registerItem("alchemists_powder", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item alchemy_paste = registerItem("alchemy_paste", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item alcohest = registerItem("alcohest", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item alghoul_bone_marrow = registerItem("alghoul_bone_marrow", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item alghoul_claw = registerItem("alghoul_claw", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item allspice = registerItem("allspice", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item arachas_eyes = registerItem("arachas_eyes", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item arachas_venom = registerItem("arachas_venom", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item archespore_tendril = registerItem("archespore_tendril", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item arenaria = registerItem("arenaria", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item balisse_fruit = registerItem("balisse_fruit", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item barghest_essence = registerItem("barghest_essence", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item basilisk_hide = registerItem("basilisk_hide", new RelicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item basilisk_venom = registerItem("basilisk_venom", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item bear_fat = registerItem("bear_fat", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item beggartick_blossoms = registerItem("beggartick_blossoms", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item berbercane_fruit = registerItem("berbercane_fruit", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item berserker_hide = registerItem("berserker_hide", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item bison_grass = registerItem("bison_grass", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item bloodmoss = registerItem("bloodmoss", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item blowball = registerItem("blowball", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item blue_lotus_flower = registerItem("blue_lotus_flower", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item bryonia = registerItem("bryonia", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item buckthorn = registerItem("buckthorn", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item calcium_equum = registerItem("calcium_equum", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item cave_troll_liver = registerItem("cave_troll_liver", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item celandine = registerItem("celandine", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item cherry_cordial = registerItem("cherry_cordial", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item chort_hide = registerItem("chort_hide", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item cockatrice_egg = registerItem("cockatrice_egg", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item cockatrice_stomach = registerItem("cockatrice_stomach", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item cortinarius = registerItem("cortinarius", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item crows_eye = registerItem("crows_eye", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item crystalized_essence = registerItem("crystalized_essence", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item cyclops_eye = registerItem("cyclops_eye", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dark_essence = registerItem("dark_essence", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item devourers_blood = registerItem("devourers_blood", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dog_tallow = registerItem("dog_tallow", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item drowner_brain = registerItem("drowner_brain", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item drowner_tongue = registerItem("drowner_tongue", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item ducal_water = registerItem("ducal_water", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item dwarven_spirit = registerItem("dwarven_spirit", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item ekimmara_hide = registerItem("ekimmara_hide", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item elemental_essence = registerItem("elemental_essence", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item endrega_embryo = registerItem("endrega_embryo", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item endrega_heart = registerItem("endrega_heart", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item ergot_seeds = registerItem("ergot_seeds", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item erynia_eye = registerItem("erynia_eye", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item essence_of_wraith = registerItem("essence_of_wraith", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item fiends_eye = registerItem("fiends_eye", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item fifth_essence = registerItem("fifth_essence", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item foglet_teeth = registerItem("foglet_teeth", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item fools_parsley_leaves = registerItem("fools_parsley_leaves", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item forktail_hide = registerItem("forktail_hide", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item gargoyle_dust = registerItem("gargoyle_dust", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item gargoyle_heart = registerItem("gargoyle_heart", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item ghouls_blood = registerItem("ghouls_blood", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item giant_centipede_discharge = registerItem("giant_centipede_discharge", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item giant_centipede_mandible = registerItem("giant_centipede_mandible", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item ginatia_petals = registerItem("ginatia_petals", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item golems_heart = registerItem("golems_heart", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item grave_hags_ear = registerItem("grave_hags_ear", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item green_mold = registerItem("green_mold", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item griffin_feathers = registerItem("griffin_feathers", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item griffins_egg = registerItem("griffins_egg", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item han_fiber = registerItem("han_fiber", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item harpy_eggs = registerItem("harpy_eggs", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item harpy_feathers = registerItem("harpy_feathers", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item harpy_talons = registerItem("harpy_talons", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item hellebore_petals = registerItem("hellebore_petals", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item honeysuckle = registerItem("honeysuckle", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item hop_umbels = registerItem("hop_umbels", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item hornwort = registerItem("hornwort", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item hydragenum = registerItem("hydragenum", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item kikimore_discharge = registerItem("kikimore_discharge", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item leshen_resin = registerItem("leshen_resin", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item light_essence = registerItem("light_essence", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item lock_of_lamia_hair = registerItem("lock_of_lamia_hair", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item longrube = registerItem("longrube", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item lunar_shards = registerItem("lunar_shards", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item mahakaman_spirit = registerItem("mahakaman_spirit", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item mandrake_cordial = registerItem("mandrake_cordial", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item mandrake_root = registerItem("mandrake_root", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item mistletoe = registerItem("mistletoe", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item moleyarrow = registerItem("moleyarrow", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nazairi_basil = registerItem("nazairi_basil", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item necrophage_hide = registerItem("necrophage_hide", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nekker_blood = registerItem("nekker_blood", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nekker_claws = registerItem("nekker_claws", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nekker_eye = registerItem("nekker_eye", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nekker_heart = registerItem("nekker_heart", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nekker_warrior_liver = registerItem("nekker_warrior_liver", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nightwraith_hair = registerItem("nightwraith_hair", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nigredo = registerItem("nigredo", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nilfgaardian_lemon = registerItem("nilfgaardian_lemon", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item nostrix = registerItem("nostrix", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item optima_mater = registerItem("optima_mater", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item phosphorus = registerItem("phosphorus", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item pringrape = registerItem("pringrape", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item puffball = registerItem("puffball", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item quebrith = registerItem("quebrith", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item quicksilver_solution = registerItem("quicksilver_solution", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item ranogrin = registerItem("ranogrin", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item rebis = registerItem("rebis", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item redanian_herbal = registerItem("redanian_herbal", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item ribleaf = registerItem("ribleaf", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item rotfiend_blood = registerItem("rotfiend_blood", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item rubedo = registerItem("rubedo", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item saltpeter = registerItem("saltpeter", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item sewant_mushrooms = registerItem("sewant_mushrooms", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item shaelmaar_dust = registerItem("shaelmaar_dust", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item shaelmaar_hair = registerItem("shaelmaar_hair", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item slyzard_scale_plate = registerItem("slyzard_scale_plate", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item specter_dust = registerItem("specter_dust", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item stammelfords_dust = registerItem("stammelfords_dust", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item sulfur = registerItem("sulfur", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item troll_hide = registerItem("troll_hide", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item vampire_blood = registerItem("vampire_blood", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item vampire_fang = registerItem("vampire_fang", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item vampire_saliva = registerItem("vampire_saliva", new MasterItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item verbena = registerItem("verbena", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item vermilion = registerItem("vermilion", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item vitriol = registerItem("vitriol", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item water_essence = registerItem("water_essence", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item water_hag_tooth = registerItem("water_hag_tooth", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item werewolf_hide = registerItem("werewolf_hide", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item werewolf_saliva = registerItem("werewolf_saliva", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item white_gull = registerItem("white_gull", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item white_myrtle_petals = registerItem("white_myrtle_petals", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item wight_ear = registerItem("wight_ear", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item wight_hair = registerItem("wight_hair", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item wine_stone = registerItem("wine_stone", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item winter_cherry = registerItem("winter_cherry", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item wolfs_liver = registerItem("wolfs_liver", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item wolfsbane = registerItem("wolfsbane", new CommonItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item wyvern_egg = registerItem("wyvern_egg", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));
    public static final Item wyvern_hide = registerItem("wyvern_hide", new MagicItem(new FabricItemSettings().group(ModItemGroup.THE_WITCHER)));

    //Foods

    private static Item registerItem(String name, Item item){
        return Registry.register(Registry.ITEM, new Identifier(TheWitcherMod.MOD_ID, name), item);
    }
    public static void RegisterModItems(){
        TheWitcherMod.LOGGER.debug("Registering Mod Items" + TheWitcherMod.MOD_ID);
    }
}
